name: Build-sphinx-docs

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to use'
        required: false
        default: '3.13'
        type: string
    
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
           python-version: ${{ inputs.python_version }}
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -U sphinx
          pip install sphinx sphinx-rtd-theme

      - name: Check for documentation
        id: check_docs
        run: |
          if [ -d docs ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Debug docs check
        run: echo "docs/ exists? ${{ steps.check_docs.outputs.exists }}"

      - name: Build HTML
        if: steps.check_docs.outputs.exists == 'true'
        shell: bash
        run: | 
          cd docs/
          make html

      - name: Install ghp-import
        if: steps.check_docs.outputs.exists == 'true'
        run: pip install ghp-import

      - name: Run ghp-import
        if: steps.check_docs.outputs.exists == 'true'
        run: | 
          ghp-import -n -p -f docs/_build/html

